/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated.connect'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthenticatedTeamTeamSlugRouteImport } from './routes/_authenticated.team.$teamSlug'
import { Route as AuthenticatedTeamTeamSlugIndexRouteImport } from './routes/_authenticated.team.$teamSlug.index'
import { Route as AuthenticatedCanvasConnIdIndexRouteImport } from './routes/_authenticated.canvas.$connId.index'
import { Route as AuthenticatedTeamTeamSlugConnectRouteImport } from './routes/_authenticated.team.$teamSlug.connect'
import { Route as AuthenticatedCanvasConnIdQueryRouteImport } from './routes/_authenticated.canvas.$connId.query'
import { Route as AuthenticatedTeamTeamSlugCanvasConnIdIndexRouteImport } from './routes/_authenticated.team.$teamSlug.canvas.$connId.index'
import { Route as AuthenticatedTeamTeamSlugCanvasConnIdQueryRouteImport } from './routes/_authenticated.team.$teamSlug.canvas.$connId.query'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTeamTeamSlugRoute =
  AuthenticatedTeamTeamSlugRouteImport.update({
    id: '/team/$teamSlug',
    path: '/team/$teamSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamTeamSlugIndexRoute =
  AuthenticatedTeamTeamSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamTeamSlugRoute,
  } as any)
const AuthenticatedCanvasConnIdIndexRoute =
  AuthenticatedCanvasConnIdIndexRouteImport.update({
    id: '/canvas/$connId/',
    path: '/canvas/$connId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamTeamSlugConnectRoute =
  AuthenticatedTeamTeamSlugConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => AuthenticatedTeamTeamSlugRoute,
  } as any)
const AuthenticatedCanvasConnIdQueryRoute =
  AuthenticatedCanvasConnIdQueryRouteImport.update({
    id: '/canvas/$connId/query',
    path: '/canvas/$connId/query',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamTeamSlugCanvasConnIdIndexRoute =
  AuthenticatedTeamTeamSlugCanvasConnIdIndexRouteImport.update({
    id: '/canvas/$connId/',
    path: '/canvas/$connId/',
    getParentRoute: () => AuthenticatedTeamTeamSlugRoute,
  } as any)
const AuthenticatedTeamTeamSlugCanvasConnIdQueryRoute =
  AuthenticatedTeamTeamSlugCanvasConnIdQueryRouteImport.update({
    id: '/canvas/$connId/query',
    path: '/canvas/$connId/query',
    getParentRoute: () => AuthenticatedTeamTeamSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/': typeof AuthenticatedIndexRoute
  '/team/$teamSlug': typeof AuthenticatedTeamTeamSlugRouteWithChildren
  '/canvas/$connId/query': typeof AuthenticatedCanvasConnIdQueryRoute
  '/team/$teamSlug/connect': typeof AuthenticatedTeamTeamSlugConnectRoute
  '/canvas/$connId': typeof AuthenticatedCanvasConnIdIndexRoute
  '/team/$teamSlug/': typeof AuthenticatedTeamTeamSlugIndexRoute
  '/team/$teamSlug/canvas/$connId/query': typeof AuthenticatedTeamTeamSlugCanvasConnIdQueryRoute
  '/team/$teamSlug/canvas/$connId': typeof AuthenticatedTeamTeamSlugCanvasConnIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/': typeof AuthenticatedIndexRoute
  '/canvas/$connId/query': typeof AuthenticatedCanvasConnIdQueryRoute
  '/team/$teamSlug/connect': typeof AuthenticatedTeamTeamSlugConnectRoute
  '/canvas/$connId': typeof AuthenticatedCanvasConnIdIndexRoute
  '/team/$teamSlug': typeof AuthenticatedTeamTeamSlugIndexRoute
  '/team/$teamSlug/canvas/$connId/query': typeof AuthenticatedTeamTeamSlugCanvasConnIdQueryRoute
  '/team/$teamSlug/canvas/$connId': typeof AuthenticatedTeamTeamSlugCanvasConnIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/team/$teamSlug': typeof AuthenticatedTeamTeamSlugRouteWithChildren
  '/_authenticated/canvas/$connId/query': typeof AuthenticatedCanvasConnIdQueryRoute
  '/_authenticated/team/$teamSlug/connect': typeof AuthenticatedTeamTeamSlugConnectRoute
  '/_authenticated/canvas/$connId/': typeof AuthenticatedCanvasConnIdIndexRoute
  '/_authenticated/team/$teamSlug/': typeof AuthenticatedTeamTeamSlugIndexRoute
  '/_authenticated/team/$teamSlug/canvas/$connId/query': typeof AuthenticatedTeamTeamSlugCanvasConnIdQueryRoute
  '/_authenticated/team/$teamSlug/canvas/$connId/': typeof AuthenticatedTeamTeamSlugCanvasConnIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/connect'
    | '/'
    | '/team/$teamSlug'
    | '/canvas/$connId/query'
    | '/team/$teamSlug/connect'
    | '/canvas/$connId'
    | '/team/$teamSlug/'
    | '/team/$teamSlug/canvas/$connId/query'
    | '/team/$teamSlug/canvas/$connId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/connect'
    | '/'
    | '/canvas/$connId/query'
    | '/team/$teamSlug/connect'
    | '/canvas/$connId'
    | '/team/$teamSlug'
    | '/team/$teamSlug/canvas/$connId/query'
    | '/team/$teamSlug/canvas/$connId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_authenticated/connect'
    | '/_authenticated/'
    | '/_authenticated/team/$teamSlug'
    | '/_authenticated/canvas/$connId/query'
    | '/_authenticated/team/$teamSlug/connect'
    | '/_authenticated/canvas/$connId/'
    | '/_authenticated/team/$teamSlug/'
    | '/_authenticated/team/$teamSlug/canvas/$connId/query'
    | '/_authenticated/team/$teamSlug/canvas/$connId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/team/$teamSlug': {
      id: '/_authenticated/team/$teamSlug'
      path: '/team/$teamSlug'
      fullPath: '/team/$teamSlug'
      preLoaderRoute: typeof AuthenticatedTeamTeamSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team/$teamSlug/': {
      id: '/_authenticated/team/$teamSlug/'
      path: '/'
      fullPath: '/team/$teamSlug/'
      preLoaderRoute: typeof AuthenticatedTeamTeamSlugIndexRouteImport
      parentRoute: typeof AuthenticatedTeamTeamSlugRoute
    }
    '/_authenticated/canvas/$connId/': {
      id: '/_authenticated/canvas/$connId/'
      path: '/canvas/$connId'
      fullPath: '/canvas/$connId'
      preLoaderRoute: typeof AuthenticatedCanvasConnIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team/$teamSlug/connect': {
      id: '/_authenticated/team/$teamSlug/connect'
      path: '/connect'
      fullPath: '/team/$teamSlug/connect'
      preLoaderRoute: typeof AuthenticatedTeamTeamSlugConnectRouteImport
      parentRoute: typeof AuthenticatedTeamTeamSlugRoute
    }
    '/_authenticated/canvas/$connId/query': {
      id: '/_authenticated/canvas/$connId/query'
      path: '/canvas/$connId/query'
      fullPath: '/canvas/$connId/query'
      preLoaderRoute: typeof AuthenticatedCanvasConnIdQueryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team/$teamSlug/canvas/$connId/': {
      id: '/_authenticated/team/$teamSlug/canvas/$connId/'
      path: '/canvas/$connId'
      fullPath: '/team/$teamSlug/canvas/$connId'
      preLoaderRoute: typeof AuthenticatedTeamTeamSlugCanvasConnIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamTeamSlugRoute
    }
    '/_authenticated/team/$teamSlug/canvas/$connId/query': {
      id: '/_authenticated/team/$teamSlug/canvas/$connId/query'
      path: '/canvas/$connId/query'
      fullPath: '/team/$teamSlug/canvas/$connId/query'
      preLoaderRoute: typeof AuthenticatedTeamTeamSlugCanvasConnIdQueryRouteImport
      parentRoute: typeof AuthenticatedTeamTeamSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedTeamTeamSlugRouteChildren {
  AuthenticatedTeamTeamSlugConnectRoute: typeof AuthenticatedTeamTeamSlugConnectRoute
  AuthenticatedTeamTeamSlugIndexRoute: typeof AuthenticatedTeamTeamSlugIndexRoute
  AuthenticatedTeamTeamSlugCanvasConnIdQueryRoute: typeof AuthenticatedTeamTeamSlugCanvasConnIdQueryRoute
  AuthenticatedTeamTeamSlugCanvasConnIdIndexRoute: typeof AuthenticatedTeamTeamSlugCanvasConnIdIndexRoute
}

const AuthenticatedTeamTeamSlugRouteChildren: AuthenticatedTeamTeamSlugRouteChildren =
  {
    AuthenticatedTeamTeamSlugConnectRoute:
      AuthenticatedTeamTeamSlugConnectRoute,
    AuthenticatedTeamTeamSlugIndexRoute: AuthenticatedTeamTeamSlugIndexRoute,
    AuthenticatedTeamTeamSlugCanvasConnIdQueryRoute:
      AuthenticatedTeamTeamSlugCanvasConnIdQueryRoute,
    AuthenticatedTeamTeamSlugCanvasConnIdIndexRoute:
      AuthenticatedTeamTeamSlugCanvasConnIdIndexRoute,
  }

const AuthenticatedTeamTeamSlugRouteWithChildren =
  AuthenticatedTeamTeamSlugRoute._addFileChildren(
    AuthenticatedTeamTeamSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTeamTeamSlugRoute: typeof AuthenticatedTeamTeamSlugRouteWithChildren
  AuthenticatedCanvasConnIdQueryRoute: typeof AuthenticatedCanvasConnIdQueryRoute
  AuthenticatedCanvasConnIdIndexRoute: typeof AuthenticatedCanvasConnIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTeamTeamSlugRoute: AuthenticatedTeamTeamSlugRouteWithChildren,
  AuthenticatedCanvasConnIdQueryRoute: AuthenticatedCanvasConnIdQueryRoute,
  AuthenticatedCanvasConnIdIndexRoute: AuthenticatedCanvasConnIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
